import { Category, ProjectProps } from "../ui/types";
import { CategoryType } from "../utils/utils";

export const categories: Record<Category, CategoryType> = {
  [Category.Branding]: { name: "Branding", color: "bg-ui-primary-blue" },
  [Category.GraphicDesign]: {
    name: "Graphic Design",
    color: "bg-ui-aquamarine",
  },
  [Category.Website]: { name: "Websites", color: "bg-ui-blue" },
  [Category.Software]: { name: "Software", color: "bg-ui-red" },
  [Category.Event]: { name: "Event Poster", color: "bg-ui-green" },
  [Category.Naming]: { name: "Naming", color: "bg-ui-dark-blue" },
  [Category.Music]: { name: "Music", color: "bg-ui-yellow" },
  [Category.Graffiti]: { name: "Graffiti", color: "bg-ui-salmon" },
  [Category.Literature]: { name: "Literature", color: "bg-ui-pink" },
};

export const projects: ProjectProps[] = [
  {
    id: "360",
    name: "360",
    date: "2016.09",
    thumbnail: "/images/360/thumbnail.png",
    shortDesc: "gra mobilna",
    assets: ["/images/360/thumbnail.png", "/images/360/asset1.png"],
    description: `360 to aplikacja mobilna, dla tych którzy uwielbiają proste, casualowe gierki.
    Gra została napisana w całości w Pythonie, dzięki Kivy, wieloplatformowemu framework’owi, który zapewnia wszelkie narzędzia by napisać, wdrożyć i przetestować aplikację mobilną na wszystkie najpopularniejsze platformy.
    Celem gry jest wykręcanie pełnych okrążeń wokół wszystkich okręgów i unikanie szarych kółek, co z biegiem czasu staje się coraz trudniejsze gdy kółka przyspieszają i dynamicznie zmieniają kierunek. Aplikacja została zaprojektowana pod urządzenia z systemem Android, a w kwietniu 2016 została opublikowana jako darmowa gierka w sklepie Google Play.
    `,
    tags: [Category.Software, Category.GraphicDesign],
    className: "bg-[#44464b]",
  },
  {
    id: "ads_buduje",
    name: "ADS Buduje",
    date: "2022.04",
    shortDesc: "branding",
    description: "identyfikacja wizualna dla sklepu z materiałami budowlanymi",
    thumbnail: "/images/ads_buduje/thumbnail.png",
    assets: ["/images/ads_buduje/asset1.png"],
    tags: [Category.Branding],
  },
  {
    id: "ads_green",
    name: "ADS Green",
    date: "2020.04",
    shortDesc: "branding, www",
    description: "identyfikacja wizualna dla firmy fotowoltaicznej, strona www",
    thumbnail: "/images/ads_green/thumbnail.png",
    assets: ["/images/ads_green/asset1.png", "/images/ads_green/asset2.png"],
    tags: [Category.Website, Category.Branding],
  },
  {
    id: "digitape",
    name: "Digitape",
    date: "2019.06",
    shortDesc: "branding, www",
    thumbnail: "/images/digitape/thumbnail.png",
    assets: ["/images/digitape/asset1.png"],
    description:
      "identyfikacja wizualna dla aplikacji archiwizującej materiały filmowe, projekt strony www",
    tags: [Category.Website, Category.Branding],
  },
  {
    id: "event",
    name: "Event Poster",
    date: "2015-2023",
    shortDesc: "seria plakatów eventowych",
    thumbnail: "/images/event/thumbnail.png",
    assets: ["/images/event/asset1.png"],
    description: `Seria plakatów z lat 2015-2023, promujących wybrane wydarzenia  organizowane przez Stowarzyszenie ARTwarium które działa formalnie od roku 2012 r. Celem stowarzyszenia jest prowadzenie działalności kulturalnej, medialnej, edukacyjnej, artystycznej oraz społecznej, zwłaszcza w zakresie organizacji i wspierania wydarzeń kulturalno – artystycznych.`,
    tags: [Category.GraphicDesign],
  },
  {
    id: "ewerestenergy",
    name: "ewerest energy",
    date: "2019.04",
    shortDesc: "identyfikacja wizualna",
    description: "identyfikacja wizualna dla firmy fotowoltaicznej",
    thumbnail: "/images/ewerest/thumbnail.png",
    assets: ["/images/ewerest/asset1.png"],
    tags: [Category.Branding],
  },
  {
    id: "garbatelemury",
    name: "garbate lemury",
    date: "2017",
    shortDesc: "album muzyczny",
    thumbnail: "/images/garbate_lemury/thumbnail.png",
    assets: ["/images/garbate_lemury/asset1.png"],
    tags: [Category.GraphicDesign, Category.Music],
    description: `projekt graficzny okładki, pudełko jak i samej płyty i przygotowanie do druku dla EP-ki punkrockowego zespołu garbate lemury, w którym odpowiadam za gitarę, chórki i słowa do kilku utworów. EP-kę „pocotamowa” nagraliśmy w 2017 roku, a za realizację nagrań odpowiadał chaos underground.`,
  },
  {
    id: "historie_rodzinne",
    name: "historie rodzinne",
    shortDesc: "książka historyczna",
    date: "2024.06",
    description:
      "książka historyczna wydana przez paniekolegoprojekt, obejmująca wydarzenia XX wieku",
    thumbnail: "/images/historie_rodzinne/thumbnail.png",
    assets: [
      "https://www.youtube.com/embed/cMMkpDd9gBw?si=rhxpvBa_c5k8Wts7&amp;controls=0",
      "/images/historie_rodzinne/asset1.png",
    ],
    tags: [Category.Literature],
  },
  {
    id: "indem",
    name: "indem odszkodowania",
    shortDesc: "branding, www",
    date: "2023.09",
    description:
      "identyfikacja wizualna dla firmy odszkodowawczej, projekt namingowy, projekt oraz wdrożenie strony www",
    thumbnail: "/images/indem/thumbnail.png",
    assets: ["/images/indem/asset1.png"],
    tags: [Category.Branding, Category.Website],
  },
  {
    id: "kosa_projects",
    name: "kosa projects",
    shortDesc: "branding",
    date: "2024.02",
    description: "",
    thumbnail: "/images/kosa/thumbnail.png",
    assets: ["/images/kosa/asset1.png"],
    tags: [Category.Branding],
  },
  {
    id: "lokal",
    name: "lokal",
    date: "2015-2023",
    shortDesc: "seria plakatów eventowych",
    thumbnail: "/images/lokal/thumbnail.png",
    description: `Seria plakatów z lat 2015-2023, promujących festiwal Lokal, organizowany przez Stowarzyszenie ARTwarium. `,
    assets: ["/images/lokal/asset1.png"],
    tags: [Category.GraphicDesign],
  },
  {
    id: "montii",
    name: "montii",
    date: "2023.02",
    shortDesc: "identyfikacja wizualna",
    thumbnail: "/images/montii/thumbnail.png",
    description: "identyfikacja wizualna dla kancelarii podatkowej",
    tags: [Category.Branding],
    assets: ["/images/montii/asset1.png"],
  },
  {
    id: "nowoczesna_sypialnia",
    name: "nowoczesna sypialnia",
    date: "2020.05",
    thumbnail: "/images/nowoczesna_sypialnia/thumbnail.png",
    tags: [Category.Branding, Category.Website],
    description: "identyfikacja wizualna dla firmy meblowej, strona www",
    assets: ["/images/nowoczesna_sypialnia/asset1.png"],
  },
  {
    id: "pdr",
    date: "2020.06",
    name: "punkt dobrych rozwiązań",
    thumbnail: "/images/pdr/thumbnail.png",
    shortDesc: "naming + branding",
    description:
      "naming oraz identyfikacja wizualna dla firmy specjalizującej się w technologii paintless dent repair",
    assets: ["/images/pdr/asset1.png"],
    tags: [Category.Branding, Category.Naming],
  },
  {
    id: "roastie",
    name: "Roastie",
    date: "2020",
    shortDesc: "branding",
    thumbnail: "/images/roastie/thumbnail.png",
    description: "identyfikacja wizualna dla restauracji",
    assets: ["/images/roastie/asset1.png"],
    tags: [Category.Branding],
  },
  {
    id: "septymole",
    name: "septymole",
    date: "2018.07",
    shortDesc: "logo",
    thumbnail: "/images/septymole/thumbnail.png",
    description: "logo dla zespołu muzycznego",
    assets: ["/images/septymole/asset1.png"],
    tags: [Category.Branding],
  },
  {
    id: "sklep_tapicera",
    name: "sklep tapicera",
    date: "2020.02",
    shortDesc: "identyfikacja wizualna",
    thumbnail: "/images/skleptapicera/thumbnail.png",
    description: "identyfikacja wizualna dla sklepu tapicerskiego",
    assets: ["/images/skleptapicera/asset1.png"],
    tags: [Category.Branding],
  },
  {
    id: "starszysyny",
    name: "starszysyny",
    date: "2022",
    description: "produkcja, projekt okładki, montaż teledysków",
    shortDesc: "album muzyczny",
    thumbnail: "/images/starszysyny/thumbnail.png",
    assets: ["/images/starszysyny/asset1.png"],
    tags: [Category.Music, Category.GraphicDesign],
  },
  {
    id: "szablony_lokalne",
    name: "Szablony LOKALne",
    shortDesc: "seria murali",
    date: "2022-2024",
    description:
      "seria 14 murali z postaciami historycznymu na terenie miejscowości Bralin, graffiti, strona www",
    tags: [Category.Graffiti, Category.Website],
    assets: [
      "https://www.youtube.com/embed/IdWoyn_0f7M?si=EvosHacTT-itmDuS&amp;controls=0",
      "/images/szablony/asset1.png",
    ],
    thumbnail: "/images/szablony/thumbnail.png",
  },
  {
    id: "szefner",
    name: "Szefner",
    shortDesc: "logo design",
    date: "2022",
    thumbnail: "/images/szefner/thumbnail.png",
    description: "logo dla zespołu muzycznego",
    assets: ["/images/szefner/asset1.png"],
    tags: [Category.Branding],
  },
  {
    id: "t4m",
    name: "Twój Format Mebli",
    shortDesc: "identyfikacja wizualna",
    date: "2024.02",
    thumbnail: "/images/t4m/thumbnail.png",
    assets: ["/images/t4m/asset1.png"],
    description: "identyfikacja wizualna dla firmy stolarskiej",
    tags: [Category.Branding],
  },
  {
    id: "techdach",
    name: "TechDach",
    shortDesc: "identyfikacja wizualna",
    date: "2023.02",
    thumbnail: "/images/techdach/thumbnail.png",
    assets: ["/images/techdach/asset1.png"],
    description: "identyfikacja wizualna dla firmy dekarskiej",
    tags: [Category.Branding],
  },
];
