import { SectionProps } from "@/ui/molecules/Section/Section";
import { ProjectProps } from "../ui/types";

export enum Section {
  Software = "Software Development",
  Branding = "Branding",
  GraphicDesign = "Graphic Design",
  Art = "Art",
}

export enum ProjectType {
  Contract = "Contract",
  Web = "Web",
  Mobile = "Mobile App",
  Branding = "Branding",
  Naming = "Naming",
  Logo = "Logo Design",
  EventPoster = "Event Poster",
  Billboard = "Billboard",
  Graphics = "Graphics",
  Music = "Music",
  Literature = "Literature",
  Graffiti = "Graffiti",
}

export const projects: ProjectProps[] = [
  {
    section: Section.Software,
    name: "Travcorp",
    className: "travcorp-section",
    date: "2020-now",
    assets: ["/images/travcorp/1.jpg"],
    tags: [ProjectType.Contract],
  },
  {
    section: Section.Software,
    className: "power-media-section",
    name: "Power Media",
    date: "2016-2020",
    assets: ["/images/powermedia/1.jpg"],
    tags: [ProjectType.Contract],
  },
  {
    section: Section.Art,
    name: "Szablony LOKALne",
    date: "2022-2026",
    bgColor: "#000",
    tags: [ProjectType.Graffiti, ProjectType.Web, "seria murali"],
    assets: [
      "https://www.youtube.com/embed/IdWoyn_0f7M?si=EvosHacTT-itmDuS&amp;amp;controls=0",
      "/images/szablony/1.jpg",
      "/images/szablony/2.jpg",
      "/images/szablony/3.jpg",
      "/images/szablony/4.jpg",
      "/images/szablony/5.jpg",
      "https://www.youtube.com/embed/p6aZ3A-bI8w?si=i2V8-v5qP-dkl3nL",
    ],
  },
  {
    section: Section.Software,
    name: "Szablony LOKALne WEB",
    date: "2025",
    tags: [ProjectType.Graffiti, ProjectType.Web, "seria murali"],
    assets: [
      "/images/szablony/6.jpg",
      "/images/szablony/4.jpg",
      "/images/szablony/8.jpg",
      "https://www.youtube.com/embed/IdWoyn_0f7M?si=EvosHacTT-itmDuS&amp;amp;controls=0",
      "/images/szablony/7.jpg",
    ],
  },
  {
    name: "Piancover",
    section: Section.Branding,
    tags: [ProjectType.Branding, ProjectType.Naming],
    date: "2025.03",
    assets: [
      "/images/piancover/5.jpg",
      "/images/piancover/1.jpg",
      "/images/piancover/2.jpg",
      "/images/piancover/3.jpg",
      "/images/piancover/4.jpg",
    ],
  },
  {
    section: Section.Art,
    name: "historie rodzinne",
    date: "2024.06",
    assets: [
      "/images/historie_rodzinne/1.jpg",
      "/images/historie_rodzinne/3.jpg",
      "https://www.youtube.com/embed/cMMkpDd9gBw?si=rhxpvBa_c5k8Wts7&amp;amp;controls=0",
      "/images/historie_rodzinne/2.jpg",
    ],
    tags: [
      ProjectType.Literature,
      ProjectType.Graphics,
      "publikacja historyczna",
    ],
  },
  {
    section: Section.Branding,
    name: "kosa projects",
    date: "2024.02",
    assets: [
      "/images/kosa/1.jpg",
      "/images/kosa/4.jpg",
      "/images/kosa/3.jpg",
      "/images/kosa/2.jpg",
    ],
    tags: [ProjectType.Branding],
  },
  {
    section: Section.Branding,
    name: "Twój Format Mebli",
    date: "2024.02",
    assets: ["/images/t4m/1.jpg", "/images/t4m/2.jpg", "/images/t4m/3.jpg"],
    tags: [ProjectType.Branding],
  },
  {
    section: Section.Software,
    name: "indem",
    date: "2023.09",
    assets: [
      "/images/indem/1.jpg",
      "/images/indem/4.jpg",
      "/images/indem/2.jpg",
      "/images/indem/3.jpg",
    ],
    tags: [
      ProjectType.Web,
      ProjectType.Branding,
      ProjectType.Naming,
      "mailing",
    ],
  },
  {
    section: Section.Branding,
    name: "TechDach",
    date: "2023.02",
    assets: ["/images/techdach/1.jpg", "/images/techdach/2.jpg"],
    tags: [ProjectType.Branding],
  },
  {
    section: Section.Branding,
    name: "Montii",
    date: "2023.02",
    tags: [ProjectType.Branding],
    assets: [
      "/images/montii/4.jpg",
      "/images/montii/1.jpg",
      "/images/montii/2.jpg",
      "/images/montii/3.jpg",
    ],
  },
  {
    name: "ADS Buduje",
    section: Section.Branding,
    tags: [ProjectType.Branding],
    date: "2022.04",
    assets: [
      "/images/ads_buduje/5.jpg",
      "/images/ads_buduje/1.jpg",
      "/images/ads_buduje/3.jpg",
      "/images/ads_buduje/4.jpg",
      "/images/ads_buduje/2.jpg",
      "/images/ads_buduje/6.jpg",
    ],
  },
  {
    section: Section.Art,
    name: "starszysyny",
    date: "2022",
    assets: [
      "/images/starszysyny/2.png",
      "https://www.youtube.com/embed/mV48BrIWMV0?si=647G-BpwORHj1BCi",
      "https://www.youtube.com/embed/yNHWXxynUvs?si=CzwmKeGxdf3WiGVe",
      "https://www.youtube.com/embed/eSEA0T1byN0?si=ZdCw11WU-JnKKoE_",
    ],
    tags: [ProjectType.Music, ProjectType.Graphics],
  },

  {
    section: Section.Branding,
    name: "Roastie",
    date: "2020",
    assets: [
      "/images/roastie/4.jpg",
      "/images/roastie/1.jpg",
      "/images/roastie/2.jpg",
      "/images/roastie/3.jpg",
    ],
    tags: [ProjectType.Branding],
  },
  {
    section: Section.Branding,
    name: "sklep tapicera",
    date: "2020.02",
    assets: [
      "/images/skleptapicera/4.jpg",
      "/images/skleptapicera/1.jpg",
      "/images/skleptapicera/2.jpg",
      "/images/skleptapicera/3.jpg",
    ],
    tags: [ProjectType.Branding],
  },
  {
    section: Section.Branding,
    name: "nowoczesna sypialnia",
    date: "2020.05",
    tags: [ProjectType.Branding, ProjectType.Web],
    assets: [
      "/images/nowoczesna_sypialnia/4.jpg",
      "/images/nowoczesna_sypialnia/3.jpg",
      "/images/nowoczesna_sypialnia/2.jpg",
      "/images/nowoczesna_sypialnia/1.jpg",
    ],
  },
  {
    date: "2020.06",
    section: Section.Branding,
    name: "punkt dobrych rozwiązań",
    assets: ["/images/pdr/1.jpg", "/images/pdr/3.jpg", "/images/pdr/2.jpg"],
    tags: [ProjectType.Branding, ProjectType.Naming],
  },
  {
    section: Section.Software,
    name: "ADS Green",
    date: "2020.04",
    assets: [
      "/images/ads_green/_1.jpg",
      "/images/ads_green/5.jpg",
      "/images/ads_green/1.jpg",
      "/images/ads_green/2.jpg",
      "/images/ads_green/4.jpg",
      "/images/ads_green/3.jpg",
    ],

    tags: [ProjectType.Web, ProjectType.Branding],
  },
  {
    section: Section.Software,
    name: "Digitape",
    date: "2019.06",
    assets: [
      "/images/digitape/5.jpg",
      "/images/digitape/1.jpg",
      "/images/digitape/2.jpg",
      "/images/digitape/3.jpg",
      "/images/digitape/4.jpg",
    ],
    tags: [ProjectType.Web, ProjectType.Branding, ProjectType.Graphics],
  },
  {
    section: Section.Branding,
    name: "ewerest energy",
    date: "2019.04",
    assets: [
      "/images/ewerest/1.jpg",
      "/images/ewerest/2.jpg",
      "/images/ewerest/3.jpg",
      "/images/ewerest/4.jpg",
      "/images/ewerest/5.jpg",
    ],
    tags: [ProjectType.Branding],
  },
  {
    section: Section.Branding,
    name: "Various projects",
    date: "2016-now",
    assets: ["/images/various_logo/1.jpg"],
    tags: [ProjectType.Logo],
  },

  {
    section: Section.Software,
    name: "360",
    date: "2016.09",
    assets: ["/images/360/3.jpg", "/images/360/2.jpg", "/images/360/1.jpg"],
    tags: [ProjectType.Mobile, ProjectType.Graphics, "gra casualowa"],
  },
  {
    section: Section.Art,
    name: "garbate lemury",
    date: "2010-2025",
    assets: [
      "/images/garbate_lemury/5.jpg",
      "https://www.youtube.com/embed/1_OhXSdOF8M?si=0mTSbqcD0KdNd6KT",
      "/images/garbate_lemury/1.jpg",
      "https://www.youtube.com/embed/pQSvhxqT9i4?si=NOUgw67O6_UaUqt2",
      "/images/garbate_lemury/2.jpg",
      "/images/garbate_lemury/3.jpg",
      "/images/garbate_lemury/4.jpg",
    ],
    tags: [ProjectType.Graphics, ProjectType.Music],
  },
  {
    section: Section.GraphicDesign,
    name: "Lokal",
    date: "2015-2023",
    assets: [
      "/images/lokal/6.jpg",
      "/images/lokal/1.jpg",
      "/images/lokal/2.jpg",
      "/images/lokal/3.jpg",
      "/images/lokal/4.jpg",
      "/images/lokal/5.jpg",
    ],
    tags: [ProjectType.Graphics, ProjectType.EventPoster],
  },
  {
    section: Section.GraphicDesign,
    name: "Artwarium",
    date: "2015-2023",
    assets: [
      "/images/artwarium/1.jpg",
      "/images/artwarium/5.jpg",
      "/images/artwarium/2.jpg",
      "/images/artwarium/3.jpg",
      "/images/artwarium/4.jpg",
    ],
    tags: [ProjectType.Graphics, ProjectType.EventPoster],
  },
];

export const sections: SectionProps[] = [
  {
    title: Section.Software,
    bgUrl: "/images/software_bg.jpg",
    color: "#D78282",
  },
  {
    title: Section.Branding,
    bgUrl: "/images/branding_bg.jpg",
    color: "#254B5C",
  },
  {
    title: Section.GraphicDesign,
    bgUrl: "/images/graphics_bg.jpg",
    color: "#3B4D81",
  },
  {
    title: Section.Art,
    bgUrl: "/images/art_bg.jpg",
    color: "#59C9A5",
  },
];
